// Loaders for the shared JSON artifacts generated by the Python side.
// Sim modules never fetch on their own; everything is passed in, so the same
// code runs in the browser and under Node (parity tests).

export async function loadJson(url) {
  const res = await fetch(url);
  if (!res.ok) {
    throw new Error(`failed to load ${url}: HTTP ${res.status}`);
  }
  return res.json();
}

export async function loadConstants(url = "../shared/physics_constants.json") {
  return Object.freeze(await loadJson(url));
}

export async function loadTrack(url = "../shared/track.json") {
  return Object.freeze(await loadJson(url));
}
